name: build

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with=dev
      - name: Lint with pylint
        run: |
          poetry run pylint edit_distance
      - name: Check types with mypy
        run: poetry run mypy edit_distance test
      - name: Check formatting with black
        run: poetry run black --check --diff edit_distance test
      - name: Get test coverage
        run: poetry run pytest --cov=. --cov-report=xml .
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry install pytest
      - name: run tests
        run: poetry run pytest .
